name: build
on:
  registry_package:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Run Trivy vulnerability scanner for php 7
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ GITHUB_ENV }}:7'
          format: 'sarif'
          output: 'trivy-php7-results.sarif'

      - name: Upload Trivy scan results of php 7 to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always() 
        with:
          sarif_file: 'trivy-php7-results.sarif'

      - name: Run Trivy vulnerability scanner for php 8
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ GITHUB_ENV }}:8'
          format: 'sarif'
          output: 'trivy-php8-results.sarif'

      - name: Upload Trivy scan results of php 8 to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always() 
        with:
          sarif_file: 'trivy-php8-results.sarif'